name: Build and Deploy
on: # 监听 master 分支上的 push 事件
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install and Build # 下载依赖 打包项目
        run: |
          npm install
          npm run build

      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@v4 # 使用别人写好的 actions
        with: # 自定义环境变量
          token: ${{ secrets.TEST_A_B }}
          branch: master
          folder: dist
          repository-name: CHZ1004/CHZ1004.github.io # 这是我的 github page 地址
          target-folder: github-actions-demo # 打包的文件将放到静态服务器 github-actions-demo 目录下
